// Real-world UA strings covering desktop + mobile + tablet across every
// browser, OS, engine and CPU architecture the library can detect.
//
// Each entry asserts only the fields that matter for that fixture — the test
// uses `expect.objectContaining`, so omitted fields are not checked.

export const fixtures = [
    // ---------------- DESKTOP ----------------

    {
        label: 'Chrome 121 / macOS 14',
        ua: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        browser: { name: 'Chrome',  major: '121' },
        engine:  { name: 'Blink' },
        os:      { name: 'macOS',   version: '10.15.7' },
        device:  { vendor: 'Apple', model: 'Macintosh', type: undefined },
        cpu:     { architecture: undefined },
    },
    {
        label: 'Chrome 121 / Windows 11',
        ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        browser: { name: 'Chrome',  major: '121' },
        engine:  { name: 'Blink' },
        os:      { name: 'Windows', version: '10' },
        device:  { vendor: undefined, model: undefined, type: undefined },
        cpu:     { architecture: 'amd64' },
    },
    {
        label: 'Chrome 121 / Windows 7',
        ua: 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        browser: { name: 'Chrome',  major: '121' },
        engine:  { name: 'Blink' },
        os:      { name: 'Windows', version: '7' },
        cpu:     { architecture: 'amd64' },
    },
    {
        label: 'Chrome 121 / Linux x86_64',
        ua: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        browser: { name: 'Chrome',  major: '121' },
        engine:  { name: 'Blink' },
        os:      { name: 'Linux' },
        cpu:     { architecture: 'amd64' },
    },
    {
        label: 'Chrome 121 / Chrome OS',
        ua: 'Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        browser: { name: 'Chrome',  major: '121' },
        engine:  { name: 'Blink' },
        os:      { name: 'Chrome OS' },
        cpu:     { architecture: 'amd64' },
    },
    {
        label: 'Chromium 121 / Linux (explicit Chromium token)',
        ua: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chromium/121.0.0.0 Chrome/121.0.0.0 Safari/537.36',
        browser: { name: 'Chromium', major: '121' },
        engine:  { name: 'Blink' },
        os:      { name: 'Linux' },
    },
    {
        label: 'Edge 121 / Windows 11',
        ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0',
        browser: { name: 'Edge',    major: '121' },
        engine:  { name: 'Blink' },
        os:      { name: 'Windows', version: '10' },
        cpu:     { architecture: 'amd64' },
    },
    {
        label: 'Edge 121 / macOS',
        ua: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0',
        browser: { name: 'Edge',    major: '121' },
        engine:  { name: 'Blink' },
        os:      { name: 'macOS' },
        device:  { vendor: 'Apple', model: 'Macintosh' },
    },
    {
        label: 'Old Edge 18 / Windows 10 (EdgeHTML)',
        ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/18.18363',
        browser: { name: 'Edge',     major: '18' },
        engine:  { name: 'EdgeHTML', version: '18.18363' },
        os:      { name: 'Windows',  version: '10' },
    },
    {
        label: 'Firefox 124 / macOS',
        ua: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 14.4; rv:124.0) Gecko/20100101 Firefox/124.0',
        browser: { name: 'Firefox', major: '124' },
        engine:  { name: 'Gecko' },
        os:      { name: 'macOS' },
    },
    {
        label: 'Firefox 124 / Windows 11',
        ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0',
        browser: { name: 'Firefox', major: '124' },
        engine:  { name: 'Gecko' },
        os:      { name: 'Windows', version: '10' },
        cpu:     { architecture: 'amd64' },
    },
    {
        label: 'Firefox 124 / Ubuntu',
        ua: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0',
        browser: { name: 'Firefox', major: '124' },
        engine:  { name: 'Gecko' },
        os:      { name: 'Linux' },
        cpu:     { architecture: 'amd64' },
    },
    {
        label: 'Firefox 124 / Linux i686',
        ua: 'Mozilla/5.0 (X11; Linux i686; rv:124.0) Gecko/20100101 Firefox/124.0',
        browser: { name: 'Firefox', major: '124' },
        os:      { name: 'Linux' },
        cpu:     { architecture: 'ia32' },
    },
    {
        label: 'Safari 17 / macOS',
        ua: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Safari/605.1.15',
        browser: { name: 'Safari',  major: '17' },
        engine:  { name: 'WebKit' },
        os:      { name: 'macOS' },
        device:  { vendor: 'Apple', model: 'Macintosh' },
    },
    {
        label: 'Opera 109 / Windows',
        ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 OPR/109.0.0.0',
        browser: { name: 'Opera',   major: '109' },
        engine:  { name: 'Blink' },
        os:      { name: 'Windows', version: '10' },
    },
    {
        label: 'Old Opera 12 / Windows (Presto)',
        ua: 'Opera/9.80 (Windows NT 6.1; WOW64) Presto/2.12.388 Version/12.18',
        browser: { name: 'Opera',   major: '9' },
        engine:  { name: 'Presto', version: '2.12.388' },
        os:      { name: 'Windows', version: '7' },
    },
    {
        label: 'IE 11 / Windows 7 (Trident + rv)',
        ua: 'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko',
        browser: { name: 'IE',      major: '11' },
        engine:  { name: 'Trident', version: '7.0' },
        os:      { name: 'Windows', version: '7' },
    },
    {
        label: 'IE 9 / Windows 7',
        ua: 'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)',
        browser: { name: 'IE',      major: '9' },
        engine:  { name: 'Trident', version: '5.0' },
        os:      { name: 'Windows', version: '7' },
    },
    {
        label: 'IE 8 / Windows XP',
        ua: 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)',
        browser: { name: 'IE',      major: '8' },
        engine:  { name: 'Trident', version: '4.0' },
        os:      { name: 'Windows', version: 'XP' },
    },

    // ---------------- iOS — phones, tablets, in-app variants ----------------

    {
        label: 'Mobile Safari / iPhone iOS 17',
        ua: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Mobile/15E148 Safari/604.1',
        browser: { name: 'Mobile Safari', major: '17' },
        engine:  { name: 'WebKit' },
        os:      { name: 'iOS',           version: '17.4' },
        device:  { vendor: 'Apple', model: 'iPhone', type: 'mobile' },
    },
    {
        label: 'Mobile Safari / iPad iOS 17',
        ua: 'Mozilla/5.0 (iPad; CPU OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 Mobile/15E148 Safari/604.1',
        browser: { name: 'Mobile Safari' },
        engine:  { name: 'WebKit' },
        os:      { name: 'iOS',           version: '17.4' },
        device:  { vendor: 'Apple', model: 'iPad',  type: 'tablet' },
    },
    {
        label: 'Mobile Safari / iPod',
        ua: 'Mozilla/5.0 (iPod touch; CPU iPhone OS 15_7_8 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.7 Mobile/15E148 Safari/604.1',
        browser: { name: 'Mobile Safari' },
        os:      { name: 'iOS',          version: '15.7.8' },
        device:  { vendor: 'Apple', model: 'iPod', type: 'mobile' },
    },
    {
        label: 'Chrome on iOS (CriOS) — engine must be WebKit',
        ua: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/121.0.6167.66 Mobile/15E148 Safari/604.1',
        browser: { name: 'Chrome',   major: '121' },
        engine:  { name: 'WebKit' },
        os:      { name: 'iOS',     version: '17.4' },
        device:  { vendor: 'Apple', model: 'iPhone', type: 'mobile' },
    },
    {
        label: 'Firefox on iOS (FxiOS) — engine must be WebKit',
        ua: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/124.0 Mobile/15E148 Safari/605.1.15',
        browser: { name: 'Firefox', major: '124' },
        engine:  { name: 'WebKit' },
        os:      { name: 'iOS' },
        device:  { vendor: 'Apple', model: 'iPhone' },
    },
    {
        label: 'Edge on iOS (EdgiOS) — engine must be WebKit',
        ua: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 EdgiOS/121.0.0.0 Mobile/15E148 Safari/604.1',
        browser: { name: 'Edge',    major: '121' },
        engine:  { name: 'WebKit' },
        os:      { name: 'iOS' },
        device:  { vendor: 'Apple', model: 'iPhone' },
    },
    {
        label: 'Opera on iOS (OPiOS) — engine must be WebKit',
        ua: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4 OPiOS/16.0.14.123484 Mobile/15E148 Safari/9537.53',
        browser: { name: 'Opera',   major: '16' },
        engine:  { name: 'WebKit' },
        os:      { name: 'iOS' },
        device:  { vendor: 'Apple', model: 'iPhone' },
    },

    // ---------------- Android — phones, tablets, vendor models ----------------

    {
        label: 'Chrome / Pixel 7 / Android 14',
        ua: 'Mozilla/5.0 (Linux; Android 14; Pixel 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36',
        browser: { name: 'Chrome',   major: '121' },
        engine:  { name: 'Blink' },
        os:      { name: 'Android', version: '14' },
        device:  { vendor: 'Google', model: 'Pixel 7', type: 'mobile' },
    },
    {
        label: 'Chrome / Samsung Galaxy S22 / Android 14',
        ua: 'Mozilla/5.0 (Linux; Android 14; SM-S901B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36',
        browser: { name: 'Chrome',    major: '121' },
        os:      { name: 'Android',   version: '14' },
        device:  { vendor: 'Samsung', model: 'SM-S901B', type: 'mobile' },
    },
    {
        label: 'Chrome / Samsung Galaxy Tab S8 / Android 13 (tablet)',
        ua: 'Mozilla/5.0 (Linux; Android 13; SM-X800) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        browser: { name: 'Chrome',    major: '121' },
        os:      { name: 'Android',   version: '13' },
        device:  { vendor: 'Samsung', model: 'SM-X800', type: 'tablet' },
    },
    {
        label: 'Samsung Internet / Galaxy S22',
        ua: 'Mozilla/5.0 (Linux; Android 14; SM-S901B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/23.0 Chrome/115.0.0.0 Mobile Safari/537.36',
        browser: { name: 'Samsung Internet', major: '23' },
        engine:  { name: 'Blink' },
        os:      { name: 'Android', version: '14' },
        device:  { vendor: 'Samsung', model: 'SM-S901B', type: 'mobile' },
    },
    {
        label: 'Edge on Android (EdgA) / Pixel',
        ua: 'Mozilla/5.0 (Linux; Android 14; Pixel 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36 EdgA/121.0.0.0',
        browser: { name: 'Edge',     major: '121' },
        engine:  { name: 'Blink' },
        os:      { name: 'Android', version: '14' },
        device:  { vendor: 'Google', model: 'Pixel 7', type: 'mobile' },
    },
    {
        label: 'Firefox on Android (mobile)',
        ua: 'Mozilla/5.0 (Android 14; Mobile; rv:124.0) Gecko/124.0 Firefox/124.0',
        browser: { name: 'Firefox', major: '124' },
        engine:  { name: 'Gecko' },
        os:      { name: 'Android', version: '14' },
        device:  { type: 'mobile' },
    },
    {
        label: 'Chrome / Xiaomi Redmi Note 11',
        ua: 'Mozilla/5.0 (Linux; Android 12; Redmi Note 11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36',
        browser: { name: 'Chrome',   major: '121' },
        os:      { name: 'Android', version: '12' },
        device:  { vendor: 'Xiaomi', type: 'mobile' },
    },
    {
        label: 'Chrome / Huawei VOG-L29',
        ua: 'Mozilla/5.0 (Linux; Android 10; HUAWEI VOG-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36',
        browser: { name: 'Chrome',   major: '121' },
        os:      { name: 'Android', version: '10' },
        device:  { vendor: 'Huawei', model: 'VOG-L29', type: 'mobile' },
    },
    {
        label: 'Chrome / OnePlus LE2123',
        ua: 'Mozilla/5.0 (Linux; Android 13; OnePlus LE2123) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36',
        browser: { name: 'Chrome',   major: '121' },
        os:      { name: 'Android', version: '13' },
        device:  { vendor: 'OnePlus', model: 'LE2123', type: 'mobile' },
    },
    {
        label: 'Generic Android tablet (no Mobile token, no known model)',
        ua: 'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
        browser: { name: 'Chrome',   major: '121' },
        os:      { name: 'Android', version: '13' },
        device:  { vendor: undefined, model: undefined, type: 'tablet' },
    },
    {
        label: 'Generic Android phone (Mobile token, no known model)',
        ua: 'Mozilla/5.0 (Linux; Android 12; Mobile) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36',
        browser: { name: 'Chrome',   major: '121' },
        os:      { name: 'Android', version: '12' },
        device:  { type: 'mobile' },
    },

    // ---------------- Windows Phone ----------------

    {
        label: 'IE Mobile / Lumia 520 / Windows Phone 8.1',
        ua: 'Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 520) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537',
        engine:  { name: 'Trident' },
        os:      { name: 'Windows Phone', version: '8.1' },
        device:  { type: 'mobile' },
        cpu:     { architecture: 'arm' },
    },

    // ---------------- CPU coverage (synthetic but realistic) ----------------

    {
        label: 'Linux aarch64 / Firefox',
        ua: 'Mozilla/5.0 (X11; Linux aarch64; rv:124.0) Gecko/20100101 Firefox/124.0',
        os:      { name: 'Linux' },
        cpu:     { architecture: 'arm64' },
    },
    {
        label: 'Linux armv7l / Firefox',
        ua: 'Mozilla/5.0 (X11; Linux armv7l; rv:124.0) Gecko/20100101 Firefox/124.0',
        os:      { name: 'Linux' },
        cpu:     { architecture: 'arm' },
    },
];
